#COMMON="common"

CXX := g++
CXXFLAGS += -Wall -fPIE

CC := gcc
CFLAGS += -pedantic -Iinclude -DCL_TARGET_OPENCL_VERSION=200

# generating header out of opencl code
HEX := xxd
HEADER_PREFIX := /* This is an automaticaly generated header consisting of hexadecimal ANSI C strings\n * based on $(notdir $(CL_SOURCES))\n */\n\n
VERTEX_SHDR_PREFIX := /* This is an automaticaly generated header consisting of hexadecimal ANSI C strings\n * based on $(notdir $(GL_VTX_SOURCE))\n */\n\n
FRAGMENT_SHDR_PREFIX := /* This is an automaticaly generated header consisting of hexadecimal ANSI C strings\n * based on $(notdir $(GL_FGT_SOURCE))\n */\n\n

LIBS := EGL GLEW GL GLU glfw OpenCL m

DIRS := . common

OBJDIR := obj

C_SOURCES := $(foreach dir, $(DIRS), $(wildcard $(dir)/*.c))
CXX_SOURCES := $(foreach dir, $(DIRS), $(wildcard $(dir)/*.cpp))
CL_SOURCES := $(wildcard common/cl/*.cl)
GL_VTX_SOURCE := common/gl/vtx.shader
GL_FGT_SOURCE := common/gl/frag.shader

C_OBJECTS := $(patsubst %.c,%.o,$(C_SOURCES))
CPP_OBJECTS := $(patsubst %.cpp,%.o,$(CXX_SOURCES))

OBJECTS += $(CPP_OBJECTS)
OBJECTS += $(C_OBJECTS)


.SUFFIXES:
.SUFFIXES: .o .c .cpp

.cpp.o:
	@echo "cpp compilation"
	$(CXX) $(CXXFLAGS) -c $< -o $@

.c.o:
	@echo "cc compilation"
	$(CC)  $(CFLAGS) -c $< -o $@

all: lagrange

## OpenCL code
.PHONY: opencl_program_source
opencl_program_source: $(CL_SOURCES)
	cat $^ > $@

common/cl_prog.h: opencl_program_source
	$(HEX) -i $< > $@

## OpenGL hexed inline code
common/gl_vertex_prog.h: $(GL_VTX_SOURCE)
	$(HEX) -i $< > $@

common/gl_fragment_prog.h: $(GL_FGT_SOURCE)
	$(HEX) -i $< > $@

## Put autogenerated message in the headers
cl_header: common/cl_prog.h
	sed -i "1 s|^|$(HEADER_PREFIX)|" $<
	@rm -f opencl_program_source

vertex_sh: common/gl_vertex_prog.h
	sed -i "1 s|^|$(VERTEX_SHDR_PREFIX)|" $<

fragment_sh: common/gl_fragment_prog.h
	sed -i	"1 s|^|$(FRAGMENT_SHDR_PREFIX)|" $<

## executive
lagrange: | cl_header vertex_sh fragment_sh $(OBJECTS)
	@echo -e "\033[0;32mcompilation lagrange\033[0;0m"
	@echo $(OBJECTS)
	$(CXX)	$(CXXFLAGS) $(OBJECTS)	$(addprefix -l,$(LIBS)) -g -o $@


###g++ -o $* ${COMMON}/shader.cpp ${COMMON}/texture.c main.c -Iinclude -lEGL -lGLEW -lGL -lGLU -lglfw -lOpenCL -lm -DCL_TARGET_OPENCL_VERSION=120


.PHONY: clean
clean:
	@echo rm -f ./*.o ./lagrange **/*.o ./common/cl_prog.h ./common/gl_fragment_prog.h ./common/gl_vertex_prog.h
	@rm -f ./*.o ./lagrange **/*.o ./common/cl_prog.h ./common/gl_fragment_prog.h ./common/gl_vertex_prog.h
